<?php
/**
 * @file
 * Provides a custom entity type name 'customentity'.
 */

/**
 * Implements hook_entity_info().
 */
function customentity_entity_info() {
  $info = array();
  // The custom CustomEntity entity is defined here.
  // See http://drupal.org/node/1026420 and http://drupal.org/node/878804
  // for more documentation.
  $info['customentity'] = array(
    // Human readable label
    'label' => t('CustomEntity'),
    // Table for storing entity data, defined in hook_schema().
    'base table' => 'customentity',
    // This helps Entity API know how to query the custom table.
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
    ),
    // A simple wrapper around the uri method in the controller class.
    'uri callback' => 'entity_class_uri',
    // Default class is 'Entity',
    'entity class' => 'CustomEntityEntity',
    // Default class is 'EntityAPIController',
    'controller class' => 'CustomEntityEntityController',
    // The information below is used to extend the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/structure/customentity',
      'controller class' => 'CustomEntityEntityUIController',
      'menu wildcard' => '%customentity',
      'file' => 'customentity.admin.inc',
    ),
    'module' => 'customentity',
    // This controls who can access entity CRUD.
    'access callback' => 'customentity_access',
    'fieldable' => TRUE,
    'bundles' => array(
      'customentity' => array(
        'label' => t('CustomEntity'),
        'admin' => array(
          'path' => 'admin/structure/customentity',
          'access arguments' => array('administer customentity'),
        ),
      ),
    ),
    'views controller class' => 'EntityDefaultViewsController',
    'view modes' => array(
      'custom_view1' => array(
        'label' => t('Custom View 1'),
        'custom settings' => FALSE,
      ),      
    ),
  );
  return $info;
}

/**
 * Implements hook_entity_property_info().
 */
function customentity_entity_property_info() {
  $info = array();
  $properties = &$info['customentity']['properties'];
  $properties['id'] = array(
    'label' => t('EID'),
    'description' => t('The unique, numeric, internal ID of the CustomEntity entity.'),
    'type' => 'integer',
    'schema field' => 'id',
  );
  $properties['label'] = array(
    'label' => t('CustomEntity entity ID'),
    'description' => t('The unique human readable ID of the CustomEntity entity.'),
    'type' => 'text',
    'schema field' => 'label',
  );
  $properties['created'] = array(
    'label' => t('Created date'),
    'description' => t('The date the CustomEntity entity was created.'),
    'type' => 'date',
    'schema field' => 'created',
  );
  $properties['updated'] = array(
    'label' => t('Updated date'),
    'description' => t('The date the CustomEntity entity was last updated.'),
    'type' => 'date',
    'schema field' => 'updated',
  );
  return $info;
}

/**
 * Implements hook_menu().
 */
function customentity_menu() {
  $items = array();
  $items['customentity/%customentity'] = array(
    'title' => 'CustomEntity entity',
    'page callback' => 'customentity_view_entity',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Menu autoloader for /customentity/%customentity.
 */
function customentity_load($id) {
  $customentity = entity_load('customentity', array($id));
  return array_pop($customentity);
}

/**
 * Callback for /customentity/ID page.
 *
 * A place to render a complete video entity.
 */
function customentity_view_entity($customentity) {
  // Use any of the view modes defined in hook_entity_info().
  $viewmode = 'full'; 
  drupal_set_title($customentity->label);
  $customentity_view = entity_view('customentity', array($customentity->id => $customentity), $viewmode);
  dsm($customentity, 'The results from entity_load()');
  dsm($customentity_view, 'The results from entity_view()');
  return $customentity_view;
}

/**
 * Access callback for customentity CRUD operations.
 */
function customentity_access($op, $customentity = NULL, $account = NULL) {
  if (($op == 'view' && user_access('view customentity', $account)) || user_access('administer customentity', $account)) {
    return TRUE;
  }
  else if (user_access('administer customentity', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function customentity_permission() {
  return array(
    'view customentity' => array(
      'title' => t('View CustomEntity Entities'),      
    ),
    'administer customentity' => array(
      'title' => t('Administer CustomEntity Entities'),
    ),
  );
}
/**
 * Custom entity class for the CustomEntity type.
 * The class being overriden is located in:
 * sites/all/modules/contrib/entity/includes/entity.inc
 */
class CustomEntityEntity extends Entity {
  /**
   * Override this in order to implement a custom default URI.
   */
  protected function defaultUri() {
    return array('path' => 'customentity/' . $this->identifier());
  }
}

/**
 * Our custom controller for the CustomEntity type.
 *
 * We're choosing to extend the controller provided by the entity module for
 * full CRUD support for item.
 *
 * The EntityAPIController is found in
 * sites/all/modules/contrib/entity/includes/entity.controller.inc
 */
class CustomEntityEntityController extends EntityAPIController {
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $build = parent::buildContent($entity, $view_mode, $langcode, $content);
    // Build page here using render arrays.
    $build['id'] = array(
      '#type' => 'markup',
      '#markup' => 'The id of this entity is ' . $entity->id . '<br>',
    );
    $build['label'] = array(
      '#type' => 'markup',
      '#markup' => 'The label of this entity is ' . $entity->label . '<br>',
    );
    $build['created'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was created on ' . date('m-d-Y', $entity->created) . '<br>',
    );
    $build['updated'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was last updated on ' . date('m-d-Y', $entity->updated) . '<br>',
    );
    
    if ($view_mode == 'custom_view1') {
      $build['custom_view1'] = array(
        '#type' => 'markup',
        '#markup' => 'This is Custom View 1',
      );
    }
    
    return $build;
  }
  
  /**
   * Override save method.
   *
   * Populate created and updated dates automatically.
   */
  public function save($entity, DatabaseTransaction $transaction = NULL) {
    if (isset($entity->is_new)) {
      $entity->created = REQUEST_TIME;
    }
    
    $entity->updated = REQUEST_TIME;
    
    return parent::save($entity, $transaction);
  }
}

/**
 * Our custom controller for the admin ui.
 *
 * The EntityDefaultUIController can be found in
 * sites/all/modules/contrib/entity/includes/entity.ui.inc
 */
class CustomEntityEntityUIController extends EntityDefaultUIController {
 /**
   * Generates the table headers for the overview table.
   */
  protected function overviewTableHeaders($conditions, $rows, $additional_header = array()) {
    $header = $additional_header;
    array_unshift($header, t('CustomEntity'));
    if (!empty($this->entityInfo['exportable'])) {
      $header[] = t('Status');
    }
    // Add operations with the right colspan.
    $header[] = array('data' => t('Operations'), 'colspan' => $this->operationCount());
    return $header;
  }

}

