<?php
/**
 * @file
 * Provides a custom entity type name 'item'.
 */

/**
 * Implements hook_entity_info().
 */
function item_entity_info() {
  $info = array();
  // The custom item entity is defined here.
  // See http://drupal.org/node/1026420 and http://drupal.org/node/878804
  // for more documentation.
  $info['item'] = array(
    // Human readable label
    'label' => t('Item'),
    // Table for storing entity data, defined in hook_schema().
    'base table' => 'item',
    // This helps Entity API know how to query the custom table.
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
    ),
    // A simple wrapper around the uri method in the controller class.
    'uri callback' => 'entity_class_uri',
    // Default class is 'Entity',
    'entity class' => 'ItemEntity',
    // Default class is 'EntityAPIController',
    'controller class' => 'ItemEntityController',
    // The information below is used to extend the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/structure/item',
      'controller class' => 'ItemEntityUIController',
      'menu wildcard' => '%item',
      'file' => 'item.admin.inc',
    ),
    'module' => 'item',
    // This controls who can access entity CRUD.
    'access callback' => 'item_access',
    'fieldable' => TRUE,
    'bundles' => array(
      'item' => array(
        'label' => t('Item'),
        'admin' => array(
          'path' => 'admin/structure/item',
          'access arguments' => array('administer item'),
        ),
      ),
    ),
    'views controller class' => 'EntityDefaultViewsController',
    'view modes' => array(
      'custom_view1' => array(
        'label' => t('Custom View 1'),
        'custom settings' => FALSE,
      ),      
    ),
  );
  return $info;
}

/**
 * Implements hook_entity_property_info().
 */
function item_entity_property_info() {
  $info = array();
  $properties = &$info['item']['properties'];
  $properties['id'] = array(
    'label' => t('EID'),
    'description' => t('The unique, numeric, internal ID of the item entity.'),
    'type' => 'integer',
    'schema field' => 'id',
  );
  $properties['label'] = array(
    'label' => t('Item entity ID'),
    'description' => t('The unique human readable ID of the item entity.'),
    'type' => 'text',
    'schema field' => 'label',
  );
  $properties['created'] = array(
    'label' => t('Created date'),
    'description' => t('The date the item entity was created.'),
    'type' => 'date',
    'schema field' => 'created',
  );
  $properties['updated'] = array(
    'label' => t('Updated date'),
    'description' => t('The date the item entity was last updated.'),
    'type' => 'date',
    'schema field' => 'updated',
  );
  return $info;
}
/**
 * Implements hook_menu().
 */
function item_menu() {
  $items = array();
  $items['item/%item'] = array(
    'title' => 'Item entity',
    'page callback' => 'item_view_entity',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Menu autoloader for /item/%item.
 */
function item_load($id) {
  $item = entity_load('item', array($id));
  return array_pop($item);
}

/**
 * Callback for /item/ID page.
 *
 * A place to render a complete video entity.
 */
function item_view_entity($item) {
  // Use any of the view modes defined in hook_entity_info().
  $viewmode = 'full'; 
  drupal_set_title($item->label);
  $item_view = entity_view('item', array($item->id => $item), $viewmode);
  dsm($item, 'The results from entity_load()');
  dsm($item_view, 'The results from entity_view()');
  return $item_view;
}

/**
 * Access callback for item CRUD operations.
 */
function item_access($op, $item = NULL, $account = NULL) {
  if (($op == 'view' && user_access('view item', $account)) || user_access('administer item', $account)) {
    return TRUE;
  }
  else if (user_access('administer item', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function item_permission() {
  return array(
    'view item' => array(
      'title' => t('View item Entities'),      
    ),
    'administer item' => array(
      'title' => t('Administer item Entities'),
    ),
  );
}
/**
 * Custom entity class for the item type.
 * The class being overriden is located in:
 * sites/all/modules/contrib/entity/includes/entity.inc
 */
class ItemEntity extends Entity {
  /**
   * Override this in order to implement a custom default URI.
   */
  protected function defaultUri() {
    return array('path' => 'item/' . $this->identifier());
  }
}

/**
 * Our custom controller for the item type.
 *
 * We're choosing to extend the controller provided by the entity module for
 * full CRUD support for item.
 *
 * The EntityAPIController is found in
 * sites/all/modules/contrib/entity/includes/entity.controller.inc
 */
class ItemEntityController extends EntityAPIController {
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $build = parent::buildContent($entity, $view_mode, $langcode, $content);
    // Build page here using render arrays.
    $build['id'] = array(
      '#type' => 'markup',
      '#markup' => 'The id of this entity is ' . $entity->id . '<br>',
    );
    $build['label'] = array(
      '#type' => 'markup',
      '#markup' => 'The label of this entity is ' . $entity->label . '<br>',
    );
    $build['created'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was created on ' . date('m-d-Y', $entity->created) . '<br>',
    );
    $build['updated'] = array(
      '#type' => 'markup',
      '#markup' => 'This entity was last updated on ' . date('m-d-Y', $entity->updated) . '<br>',
    );
    
    if ($view_mode == 'custom_view1') {
      $build['custom_view1'] = array(
        '#type' => 'markup',
        '#markup' => 'This is Custom View 1',
      );
    }
    
    return $build;
  }
  
  /**
   * Override save method.
   *
   * Populate created and updated dates automatically.
   */
  public function save($entity, DatabaseTransaction $transaction = NULL) {
    if (isset($entity->is_new)) {
      $entity->created = REQUEST_TIME;
    }
    
    $entity->updated = REQUEST_TIME;
    
    return parent::save($entity, $transaction);
  }
}

/**
 * Our custom controller for the admin ui.
 *
 * The EntityDefaultUIController can be found in
 * sites/all/modules/contrib/entity/includes/entity.ui.inc
 */
class ItemEntityUIController extends EntityDefaultUIController {
 /**
   * Generates the table headers for the overview table.
   */
  protected function overviewTableHeaders($conditions, $rows, $additional_header = array()) {
    $header = $additional_header;
    array_unshift($header, t('Item'));
    if (!empty($this->entityInfo['exportable'])) {
      $header[] = t('Status');
    }
    // Add operations with the right colspan.
    $header[] = array('data' => t('Operations'), 'colspan' => $this->operationCount());
    return $header;
  }

}

